#!/bin/sh

# Install the default configurations here using the install hook so that the
# user can also adjust the configuration as needed

cat > ${SNAP_COMMON}/haproxy.cfg << EOF
global
	log /dev/log	local0
	log /dev/log	local1 notice
	chroot "%[env(SNAP)]/var/lib/haproxy"
	stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
	stats timeout 30s
	# Run as snap root user
	user root
	group root

	# Default SSL material locations
	ca-base "%[env(SNAP)]/etc/ssl/certs"
	crt-base "%[env(SNAP)]/etc/ssl/private"

defaults
	log	global
	mode	http
	option	httplog
	option	dontlognull
	timeout connect 5000
	timeout client  50000
	timeout server  50000
	errorfile 400 "%[env(SNAP)]/etc/haproxy/errors/400.http"
	errorfile 403 "%[env(SNAP)]/etc/haproxy/errors/403.http"
	errorfile 408 "%[env(SNAP)]/etc/haproxy/errors/408.http"
	errorfile 500 "%[env(SNAP)]/etc/haproxy/errors/500.http"
	errorfile 502 "%[env(SNAP)]/etc/haproxy/errors/502.http"
	errorfile 503 "%[env(SNAP)]/etc/haproxy/errors/503.http"
	errorfile 504 "%[env(SNAP)]/etc/haproxy/errors/504.http"

frontend serial-vault
	bind :80
	default_backend jellyfin

backend jellyfin
	server jellyfin localhost:8096

EOF

cat > ${SNAP_COMMON}/haproxy-ssl.cfg << EOF
global
	log /dev/log	local0
	log /dev/log	local1 notice
	chroot "%[env(SNAP)]/var/lib/haproxy"
	stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
	stats timeout 30s
	# Run as snap root user
	user root
	group root

	# Default SSL material locations
	ca-base "%[env(SNAP)]/etc/ssl/certs"
	crt-base "%[env(SNAP)]/etc/ssl/private"

	# generated 2022-02-04, Mozilla Guideline v5.6, HAProxy 2.0.13, OpenSSL 1.1.1f, modern configuration
	# https://ssl-config.mozilla.org/#server=haproxy&version=2.0.13&config=modern&openssl=1.1.1f&guideline=5.6
	# modern configuration
	ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
	ssl-default-bind-options prefer-client-ciphers no-sslv3 no-tlsv10 no-tlsv11 no-tlsv12 no-tls-tickets

	ssl-default-server-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
	ssl-default-server-options no-sslv3 no-tlsv10 no-tlsv11 no-tlsv12 no-tls-tickets

defaults
	log	global
	mode	http
	option	httplog
	option	dontlognull
	timeout connect 5000
	timeout client  50000
	timeout server  50000
	errorfile 400 "%[env(SNAP)]/etc/haproxy/errors/400.http"
	errorfile 403 "%[env(SNAP)]/etc/haproxy/errors/403.http"
	errorfile 408 "%[env(SNAP)]/etc/haproxy/errors/408.http"
	errorfile 500 "%[env(SNAP)]/etc/haproxy/errors/500.http"
	errorfile 502 "%[env(SNAP)]/etc/haproxy/errors/502.http"
	errorfile 503 "%[env(SNAP)]/etc/haproxy/errors/503.http"
	errorfile 504 "%[env(SNAP)]/etc/haproxy/errors/504.http"

frontend jellyfin
	mode    http
	bind    :443 ssl crt "%[env(SNAP)]/ssl.crt" alpn h2,http/1.1
	bind    :80
	redirect scheme https code 301 if !{ ssl_fc }
	default_backend jellyfin

backend jellyfin
	server jellyfin localhost:8096

EOF
